### ISSUE TITLE
Sysex to set LED color directly (raw) needed

### ISSUE THREAD

**Issue by brunchboy** [Ableton/push-interface#12]
This was originally discussed in #2 and that was closed because I was able to work around the lack of such a command by building additional infrastructure in my own program. But this past week I have been helping another developer figure out how to do this in another language, and that drove home that it is really breathtaking the amount of code that the Push 2 requires in order to accomplish something which is very simple on other RGB grid controllers, including the original Push.

On most grid controllers, when you want to set an RGB LED to a particular arbitrary RGB color, you:
1. Send a Sysex command specifying the LED and the desired R, G, and B values.

That’s it. There is often even a facility to efficiently set multiple LEDs by repeating the R, G, and B values within the same Sysex message, and there is a defined order which identifies the LEDs that will be affected. So on one controller that I support, it is possible to update the entire 8&times;8 pad grid with a single Sysex message.

On the Push 2, here is what is currently required:
1. Allocate a data structure in which you can store the entire current state of the palette of 128 RGB+W color values. (This is necessary even if you don’t care about restoring the old state of the palette for Live, because you cannot set an RGB palette entry without also specifying a W value that will affect the monochrome LEDs.)
2. Loop over all 128 palette entries, sending a Sysex message which queries the current R, G, B, W values for that entry, receive the response, and store that for future reference.
3. Come up with an assignment of LEDs to palette entries, so each LED gets to “own” a palette entry that will control its color, and not affect other LEDs. This is complicated by the fact that the LEDs which respond to MIDI notes have some overlap in note numbers with the control values used by LEDs which respond to MIDI CC messages. But at least there are enough palette entries that it is possible.
4. All of the above steps were needed before you can even think about setting an LED’s color. But once they are accomplished, you can proceed. Look up the palette entry which you assigned to the LED whose color you want to change. Find the W value you stored for that palette entry, then send the Sysex command to update that palette entry to your desired R, G, B values, along with the W value that you stored in step 2.
5. Then send a Note-On or CC message telling that LED to use the palette entry you have just updated.
6. You can repeat steps 4 and 5 as often as you need, but when you are exiting your interface (either permanently, or to leave User mode and return to Live), you need to loop over your stored palette entries and send the Sysex commands to restore them all to the values that you stored.

Although this can be done, it should be clear that it is vastly more complicated and far more work than for any other controller. This work must be duplicated by any developer and language which wants to use the Push 2 with the full range of possible colors, and thus reduces the number of people who will even try.

Please make it easy for people to build this kind of interface on the Push 2 by adding a Sysex message which directly sets the color of an LED without using or affecting the palette. Then people who want to use the palette interface can continue to do so, and people who want to use an RGB interface can do so easily without worrying about interfering with the palette.

It would be nice, if possible, to have this Sysex allow you to set the colors of multiple LEDs in one message by sending multiple color values, but that is far less of an issue than simply making it straightforward to set an LED’s color.

It would also be nice to be able to set the brightness of a monochrome LED in a similar direct manner, either with a separate Sysex message which takes a single 8-bit brightness value, or by having the same Sysex message which works for RGB LEDs also work for monochrome LEDs, translating the RGB value to a corresponding brightness level (ideally, using the perceived brightness, which would be the square root of 0.299 &times; R&sup2; + 0.587 &times; G&sup2; + 0.114 &times; B&sup2;).

**Comment by brunchboy** [comment]
I took another look at the note and control buttons in the overall interface diagram, and have taken the liberty of proposing some details for a new pair of sysex messages which could add this feature in a very convenient way for client software like mine. (The numbers I have chosen are completely arbitrary, I just picked ones that are not currently used in the documented interface; if you choose to implement something like this, pick numbers that make more sense based on your implementation!)

| Command ID | Command Name |
|-------------|---------------|
| 0x30 | Set Note-Based LED RGB Color |
| 0x31 | Set CC-Based LED RGB Color |

The first would be used to set the color of any LED which responds to Note-On messages, the second to set the color of any LED which responds to CC messages. Two separate commands are used because of the overlap between note numbers and CC numbers in the two kinds of LEDs; in this way, the LED can be identified without ambiguity. The command structure would be (following the SOX and device identification preamble, `[0xF0 0x00 0x21 0x1D 0x01 0x01]`):

| Byte | Description |
| ------ | ----------------|
| `0x30` | Set Note-Based LED RGB Color command identifier |
| _led_ | Identify which LED to set, a value from `36` to `99`.
| _r (LSB)_ | lower 7 bits of Red color |
| _r (MSB)_ | higher 1 bit of Red color |
| _g (LSB)_ | lower 7 bits of Green color |
| _g (MSB)_ | higher 1 bit of Green color |
| _b (LSB)_ | lower 7 bits of Blue color |
| _b (MSB)_ | higher 1 bit of Blue color |

In the simplest implementation, that would be all you could send. If you could support it, allowing the sender to include additional sets of six RGB bytes and have them apply to the next-higher-number LED, to set multiple LEDs in one message, would be excellent. There may be limits on how long a sysex message you can accommodate, but even if this approach cannot be used to set the color of the entire pad grid in one message, documenting that we could set (for example) four LEDs at a time this way would improve the speed of large-scale pad updates.

In response to this message, the Push 2 would change the color of the specified LED(s) to the specified RGB value, without regard to the color palette, and without affecting any color palette entry. The LED would stay that color until it receives a Note-On message to switch it back to color palette mode, or it receives another direct RGB color sysex message.

It would be nice if an LED set in this way could still participate in animations, etc., but if you do not have enough memory to store the raw RGB values for each LED that would be required to support this, then it would be fine if such LEDs were frozen at the specified color until they receive a Note-On message to reassign them to a palette entry. (This could be implemented by assigning them an illegal palette entry of, for example 255, when they have been set to a direct RGB value.)

For LEDs which respond to CC messages, the process is essentially the same:

| Byte | Description |
| ------ | ----------------|
| `0x31` | Set CC LED RGB Color command identifier |
| _led_ | Identify which LED to set, a value from `3` to `118`.
| _r (LSB)_ | lower 7 bits of Red color |
| _r (MSB)_ | higher 1 bit of Red color |
| _g (LSB)_ | lower 7 bits of Green color |
| _g (MSB)_ | higher 1 bit of Green color |
| _b (LSB)_ | lower 7 bits of Blue color |
| _b (MSB)_ | higher 1 bit of Blue color |

Because these LEDs have gaps in their numbering scheme, if you want to support setting multiple LEDs with a single message, it may be desirable to specify the next LED number before the next set of color values. But if you can only support a few LEDs per message, for space reasons, then it may be better to simply behave the same way as the note-based command, and allow you to set the colors of a series of LEDs whose numbers are sequential by including additional sets of six color bytes, rather than wasting space on extra LED number bytes.

As I noted in my original issue, if the LED receiving this message is monochrome, it would of course not display a color, but rather its brightness would be determined by the perceived brightness of the RGB color.

And, of course, if the LED number supplied does not correspond to an actual LED, the color values would simply be ignored.

If you could do something like this, it would make the Push 2 an even more incredibly useful controller!

**Comment by brunchboy** [comment]
As an alternative to converting RGB colors to effective brightnesses for the monochrome LEDs, there could be a third new sysex command:

| Byte | Description |
| ------ | ----------------|
| `0x32` | Set CC LED Monochrome Brightness command identifier |
| _led_ | Identify which LED to set, a value from `3` to `118`.
| _w (LSB)_ | lower 7 bits of white brightness |
| _w (MSB)_ | higher 1 bit of white brightness |

If you can support setting multiple LEDs by adding additional pairs of brightness bytes, it would be possible to fit more LEDs in smaller commands this way.

You could make it illegal to pass a color LED to this command (and to pass a monochrome LED to command `0x31`, in which case its range of legal LED numbers would be from `20` to `109`&mdash;although of course there is alternation in the ranges). Or, if you wanted to be fancy, passing a color LED to the monochrome command would set it to white at the specified brightness level. (And for maximum fanciness and flexibility, this new command could be combined with the full-featured version of `0x31`, so you could set the brightness of the monochrome LEDs either way too.)

So many options! But any of these choices would be a wonderful, hugely appreciated improvement, making it vastly easier for new projects to work with non-palette-based LED coloring.

**Comment by rsu-ableton** [comment]
We found the workaround to use a different color number for each LED and then only manipulate the respective color palette entry. For certain use cases this turns out to be fast enough. Providing a way to circumvent the color processing in the firmware turns out to be too complicated (and resource hungry).
