### ISSUE TITLE
push-interface not work

### ISSUE THREAD

**Issue by ars787** [Ableton/push-interface#23]
Hi! I need  help, technical support ableton do not know what's the matter. The display does not show waveforms of samples, signal levels and notes in the clip mode. The remaining functions work fine. Reinstalling windows or drivers did not work. 

https://www.youtube.com/watch?v=66wvhHcoDvc   
This video shows the problem

**Comment by rsu-ableton** [comment]
Hello, the display in Push2 doesn't make a difference of what it shows, waveforms, texts, icons,
so this issue doesn't belong here. From what I can say it looks like an issue, the sampler should not say "Press browse to load a sample". I've repeated the steps you did and for me it worked with Live 10.0.2. Please ask the Live application support for help at https://help.ableton.com/hc/en/requests/new .
Thank you!
