### ISSUE TITLE
Controlling Led's is very slow

### ISSUE THREAD

**Issue by KoSv** [Ableton/push-interface#30]
hi,
perhaps I'm making some rookie mistake, but when I send midi over USB to turn the Button LED's on and off I'm getting a very slow visual update response.
Reading the MIDI specs, I realized that this behavior is actually expected -> for a simple 3 byte massage like NoteOn send over USB takes 3ms - 5ms.
If you control (like in the manual stated) 64 led's this way, it scales up to 320ms! (knightrider effect)
So, is there a much more efficient way to control the LED's ?
thanks and cheers!

**Comment by brunchboy** [comment]
That really depends what you mean by slow. It’s never going to be as fast as a display-oriented batch protocol (like the one that controls the display in the Push 2), but it’s fast enough to do animations on; here is a section of my presentation on the Push interface I built for my lighting controller that shows the startup animation when the Push is detected (this was filmed before the Push 2 came out, my interface is even nicer on that now): https://youtu.be/mvNN0SMMZDQ?t=1916

**Comment by brunchboy** [comment]
Note that there are pauses in that animation to intentionally give that “wipe” effect. When I’m actually updating the pads in my UI loop, I send only color changes, and don’t send anything to pads which are unchanged. But even when I have to swap out palettes before sending the note (many more bytes required!) it is fast enough to feel responsive even when several buttons are smoothly changing color, and when the user is paging around between banks of buttons: https://youtu.be/mvNN0SMMZDQ?t=1945

Perhaps you are using a slow USB interface?

**Comment by KoSv** [comment]
> That really depends what you mean by slow. 

like I stated: 320ms fastest update on 64 led's... (5ms per led noteOn() command)

> Perhaps you are using a slow USB interface?

yes perhaps is this the main problem.. I'm on teensy3.6 where teensy is the USB host.

**Comment by KoSv** [comment]
On your presentation there is no lag at all...

**Comment by brunchboy** [comment]
Yes, it sounds like a USB host speed limitation then.

**Comment by KoSv** [comment]
Yes. Thank a lot! 
This helped narrowing my problem! 
Cheers and greets from Germany!
