### ISSUE TITLE
Arm/solo multiple tracks

### ISSUE THREAD

**Issue by tehlol** [Ableton/push-interface#4]
Hey there! Loving the Push2, it's like having my hands on Ableton.

That being said, I find it necessary or useful to arm and/or solo multiple tracks. It doesn't seem as if there's a straightforward way to do that. Would it be easy to hack together?

**Comment by git-moss** [comment]
I explain how to do it in the video: https://www.youtube.com/watch?v=P3NBcdmtzmI
Also see the Wiki: https://github.com/git-moss/Push4Bitwig/wiki
 Mute - Push 1: Selects track mute state of 2nd row. Push 2: Mutes the currently selected track. Long press for the Push 1 behaviour. Lock it with Shift+Solo.
Solo - Push 1: Selects track solo state of 2nd row. Push 2: Solos the currently selected track. Long press for the Push 1 behaviour. Lock it with Shift+Solo.

**Comment by tehlol** [comment]
Thanks for that @git-moss but what you've presented is for Bitwig, I'm looking specifically for this feature to be available in the Ableton interface.

**Comment by git-moss** [comment]
Uh, sorry. I thought that Mail came from another direction :-)

**Comment by git-moss** [comment]
Oh but by the way, I think it works the same in the current Ableton Beta.
