### ISSUE TITLE
Push 1 spec?

### ISSUE THREAD

**Issue by samdoshi** [Ableton/push-interface#5]
Thank you for releasing the spec for the Push 2, I think it will increase it's longevity as it can have an existence beyond Live, anything that keeps electronics of the scrapheap is good by me, I wish more companies would be as open and as hacker friendly.

Would you also consider releasing a similar document for the Push 1? There's a lot of information out there already, but it would be nice to have an official document, particularly to document some of the more complex aspects.

I'm sure there are lots of us Push 1 owners that would rather keep our Pushes (in addition to buying a Push 2 for use with Live), precisely because they are amazing controllers that can be used in alternative creative ways.

**Comment by rsu-ableton** [comment]
The main reason why we did not publish specs for Push 1 is that it was engineered by AKAI professional, using AKAI sysex messages, firmware etc. I'll put the request on the wish list.

**Comment by brunchboy** [comment]
Another possible solution would be a community-curated Push 1 specification as a separate open-source project. I could contribute things that I have discovered in building my Afterglow interface with it. I agree this would be nice to have, but there are other things I’d rather see the Ableton engineers spending their time on. :wink:
