### ISSUE TITLE
Section or page listing related libraries?

### ISSUE THREAD

**Issue by brunchboy** [Ableton/push-interface#6]
Thanks to this excellent documentation, I have implemented a library, [wayang](https://github.com/brunchboy/wayang), that makes it incredibly easy to draw to the Push display from any Java program—and I’m sure I wont be the only person doing something like that. It might be nice if you could add a section or page here to point people at such third-party solutions that can help them build amazing things with Push 2.

**Comment by rsu-ableton** [comment]
Good idea. Put it on the wish list. Let's see what we can do.

**Comment by brunchboy** [comment]
Cool, I look forward to seeing what you come up with. In the mean time, I have pretty much finished building the Afterglow interface for Push 2 using the above-linked wayang library. I also added a feature to make it easy to record little interface movies, like this one:
![example](https://cloud.githubusercontent.com/assets/2228869/14064072/88ed05be-f3b8-11e5-97c3-1be816d4acfe.gif)

I just love what you have enabled me to create thanks to this documentation! Thank you again.

**Comment by rsu-ableton** [comment]
Links added
