### ISSUE TITLE
Change in touch strip LED bar behavior?

### ISSUE THREAD

**Issue by brunchboy** [Ableton/push-interface#8]
On the original Push, when the Touch Strip was configured to display pitch bend values as a bar which starts at the bottom, and the value was set to the lowest possible pitch bend value, all the LEDs were off. On the Push 2, in this state, it seems the bottom LED remains on. Is this an intentional change? And even if so, is there any way to obtain the previous behavior?

**Comment by rsu-ableton** [comment]
Yes, this is intentional, to have a clear indication where the pitch bend is. If you want to simulate the Push1 behavior, you could set the configuration flags to 0x1100011, so that the LEDs are controlled by the host using sysex, and update the LEDs when you receive pitch bend messages, if receiving the pitch bend and sending sysex is possible in your case.

**Comment by brunchboy** [comment]
Thanks for clarifying this. I had wanted to be able to turn the LEDs off to tell the user when the touch strip has no effect. It’s easiest to use pitch bend values and your thoughtful point/bar center/bottom modes to draw the states I want than computing and sending the SysEx values, but I can switch the touch strip to SysEx mode when I want to actually turn it off, and then back to receiving pitch bend when I want it active again. I was just wondering if there were an easier way to get backward-compatible behavior. But this is a fine answer.

Happily, the Push 2 touch strip responds to mode changes much more rapidly than the original Push. On that one I had to wait a while after changing the mode before I could update the value. Now I can do it immediately, which is a significant improvement.

Thank you.

**Comment by brunchboy** [comment]
Oh, perhaps this difference (or the current behavior) is worth documenting in this manual? Or perhaps it is not worth it, since the previous behavior was undocumented, and I may be the only person in the world who was relying on it? :smile:
