### ISSUE TITLE
Is there any way to associate a particular graphical display with a particular MIDI port?

### ISSUE THREAD

**Issue by brunchboy** [Ableton/push-interface#9]
I realize that few people will be lucky enough to have multiple Push 2 devices to connect to their software, but so far I have been able to support multiple controllers just fine. When it comes to Push 2, however, I need to be sure that I am drawing on the same display that I am sending MIDI commands to, and those now occur over different communication layers to different endpoints.

When multiple Push 2s are connected, is there any way to determine which display interface corresponds with which MIDI ports?

**Comment by rsu-ableton** [comment]
This depends on the OS and the library used to interface with the MIDI ports.
At the moment I have no further information to give you, sorry.

**Comment by brunchboy** [comment]
Afterglow works for running stage lights on Linux, Windows, and Mac OS X, so eventually I would like to know the answer for all platforms. I am a coauthor of the MIDI library we are using on Mac OS X, [CoreMIDI4J](https://github.com/DerekCook/CoreMidi4J), so hopefully I am well equipped to understand the information when it becomes available. But as I said, this is not an urgent question, I do not anticipate many users wanting to hook up multiple Push 2 interfaces at once. (Although I can tell you that running a light show with a Push, a Push 2, and a couple other grid controllers, each bound to different show control windows, is an exhilarating experience! :grinning: )

**Comment by brunchboy** [comment]
Might it be possible someday to offer an easier solution to this, by adding a way to get the device serial number over the display interface as well? Then by simply comparing the values obtained via MIDI and via libusb, one could identify which display was associated with which MIDI ports.

**Comment by rsu-ableton** [comment]
Put the following request into the wish list:
 - allow to obtain the identity (e.g. the serial number) over the display interface
